[cns_nodes]
gpu-node ansible_host=10.86.9.190

[cns_nodes:vars]
ansible_user=nvidia
ansible_password=nvidia3D!
ansible_become=true
ansible_become_password=nvidia3D!
ansible_python_interpreter=/usr/bin/python3
