---
- name: Prepare the host
  ansible.builtin.include_tasks: prereqs.yml

- name: Install containerd
  ansible.builtin.include_tasks: containerd.yml

- name: Install Kubernetes packages
  ansible.builtin.include_tasks: kube_packages.yml

- name: Bootstrap the cluster
  ansible.builtin.include_tasks: kubeadm.yml

- name: Install Calico
  ansible.builtin.include_tasks: calico.yml
